# Generated by Django 3.0.1 on 2020-08-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('machineID', models.IntegerField(max_length=500)),
                ('imgID', models.IntegerField()),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('machineID', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='companycontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=40)),
                ('addr', models.CharField(max_length=40)),
                ('telinfo', models.CharField(max_length=11)),
                ('faxinfo', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='customercontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('telinfo', models.CharField(max_length=11)),
                ('mobilinfo', models.CharField(max_length=11)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='datasheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cateID', models.IntegerField()),
                ('machineID', models.IntegerField()),
                ('filepath', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='imageLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('itemID', models.IntegerField()),
                ('fpath', models.ImageField(upload_to='')),
                ('descr', models.CharField(max_length=400)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('categoryID', models.IntegerField()),
                ('machineID', models.IntegerField()),
                ('imgID', models.IntegerField()),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Mahine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maincategoryID', models.IntegerField()),
                ('imgId', models.IntegerField()),
                ('summary', models.CharField(max_length=500)),
                ('character', models.IntegerField()),
                ('techspec', models.IntegerField()),
                ('stdequip', models.IntegerField()),
                ('attach', models.IntegerField()),
                ('descr', models.CharField(max_length=500)),
                ('datash', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stdequipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('machineID', models.IntegerField(max_length=500)),
                ('imgID', models.IntegerField()),
                ('descr', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='techspec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('machineid', models.IntegerField()),
                ('param', models.CharField(max_length=60)),
            ],
        ),
    ]
