# Generated by Django 3.0.1 on 2020-09-14 07:06

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='companycontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=40)),
                ('addr', models.CharField(max_length=40)),
                ('telinfo', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('faxinfo', phone_field.models.PhoneField(blank=True, help_text='Contact fax number', max_length=31)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='customercontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('telinfo', models.CharField(max_length=11)),
                ('mobilinfo', models.CharField(max_length=11)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='datasheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('filepath', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='imageLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='images')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='techspec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('param', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='stdequipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('descr', models.CharField(max_length=400)),
                ('imgID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdequipimage', to='machine.imageLibrary')),
            ],
        ),
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=400)),
                ('imgID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcimagelibrary', to='machine.imageLibrary')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=500)),
                ('descr', models.CharField(max_length=2000)),
                ('attach', models.ManyToManyField(blank=True, related_name='attachment', to='machine.attach')),
                ('character', models.ManyToManyField(blank=True, related_name='characteristic', to='machine.characteristic')),
                ('datash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasheet', to='machine.datasheet')),
                ('imgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mimages', to='machine.imageLibrary')),
                ('maincategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinecategory', to='machine.MachineCategory')),
                ('stdequip', models.ManyToManyField(blank=True, related_name='standardequipment', to='machine.stdequipment')),
                ('techspec', models.ManyToManyField(blank=True, related_name='techspec', to='machine.techspec')),
            ],
        ),
        migrations.AddField(
            model_name='attach',
            name='imgID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachimage', to='machine.imageLibrary'),
        ),
    ]
