# Generated by Django 3.0.1 on 2020-09-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelibrary',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imagelibrary',
            name='width',
        ),
    ]
