# Generated by Django 3.0.1 on 2020-09-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20200914_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='attach',
            field=models.ManyToManyField(blank=True, null=True, related_name='attachment', to='machine.attach'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='character',
            field=models.ManyToManyField(blank=True, null=True, related_name='characteristic', to='machine.characteristic'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='stdequip',
            field=models.ManyToManyField(blank=True, null=True, related_name='standardequipment', to='machine.stdequipment'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='techspec',
            field=models.ManyToManyField(blank=True, null=True, related_name='techspec', to='machine.techspec'),
        ),
    ]
