# Generated by Django 3.0.1 on 2020-09-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_auto_20200916_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='character',
            field=models.ManyToManyField(blank=True, null=True, related_name='machines', to='machine.characteristic'),
        ),
    ]
