# Generated by Django 3.0.1 on 2020-09-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20200918_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='subject',
            field=models.CharField(default='request', max_length=200),
        ),
    ]
