# Generated by Django 3.0.1 on 2020-09-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_customercontact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
